# Generated by Django 5.2.7 on 2025-11-02 23:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OrgaoFiscalizado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=200, unique=True)),
                ("endereco", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "cnpj",
                    models.CharField(blank=True, max_length=18, null=True, unique=True),
                ),
                ("contato", models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Fiscalizacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_fiscalizacao", models.DateTimeField(auto_now_add=True)),
                ("titulo", models.CharField(max_length=255)),
                ("descricao", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("EM_ANALISE", "Em Análise"),
                            ("REGULAR", "Regular"),
                            ("IRREGULAR", "Irregular"),
                        ],
                        default="EM_ANALISE",
                        max_length=20,
                    ),
                ),
                (
                    "fiscalizador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "orgao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="fiscalizacao.orgaofiscalizado",
                    ),
                ),
            ],
        ),
    ]
